### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [grmasa/Sound-Toggle#2]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by hartwork** [comment]
@mondlicht-und-sterne I do not see screenshots at https://f-droid.org/en/packages/com.grmasa.soundtoggle/ today. Wehere there any when you closed the ticket as completed in 2021?

**Comment by grmasa** [comment]
> @mondlicht-und-sterne I do not see screenshots at https://f-droid.org/en/packages/com.grmasa.soundtoggle/ today. Were there any when you closed the ticket as completed in 2021?

I never added screenshots but if you want I can add them.

**Comment by hartwork** [comment]
@grmasa I think their main use would be to speed up answering the question if Sound Toggle is what the user is looking for. I personally needed to read to the "Normal, Vibrate and Silent" at the very end of the description to know and had no idea what QuickSettings are, just a vague guess what it could be. I believe a screenshot with the Sound Toggle button already added and in action would be great to have, yes please! 
Btw do you know what version of Android they removed the stock button for it? Android 8 still had it I believe? I have Android 13 here and very happy I found your Sound Toggle :pray:

**Comment by grmasa** [comment]
@hartwork I added two screenshots with latest commit. Did make the app purpose more clear?

**Comment by hartwork** [comment]
@grmasa I found them in 184b77683406caaeaab1f7a7100d08bd67c08434. I think something like an orange rectangle around the button would help, right now the other enabled buttons are steeling the show and it's not clear what to look for before you found it without some annotation. I can make a pull request for a demo as needed.

**Comment by hartwork** [comment]
@grmasa PS: A bit like this:
![1](https://user-images.githubusercontent.com/1577132/215279244-37d82b61-d79e-41e2-8f31-08ffa7a5074a.png)

**Comment by grmasa** [comment]
@hartwork Feel free! thank you for your suggestions!

**Comment by hartwork** [comment]
@grmasa alright, pull requesting coming soonish, today for sure.
