### ISSUE TITLE
New sound mode

### ISSUE THREAD

**Issue by tuch96** [grmasa/Sound-Toggle#3]
When "silent" is activated, no more messages are displayed. It seems that the "do not disturb" mode is then active. Would it be possible to integrate another setting that mutes the phone but still displays the messages?

Thanks!!

**Comment by grmasa** [comment]
The silent is Do not Disturb so you can change the DND settings of your device and allow message display.

**Comment by tuch96** [comment]
This works very well - thanks! I use your app every day. It's really a very effective app. Many thanks for it!

**Comment by grmasa** [comment]
Glad to hear it! Thank you!

**Comment by hartwork** [comment]
@grmasa many thanks from me for this app as well! :+1:
