### ISSUE TITLE
Add a toggle to Hide app from launcher after successful setup

### ISSUE THREAD

**Issue by Filifek** [grmasa/Sound-Toggle#6]
Hello, so first of all thank you for making this app, I was really annoyed that Pixel does not have silence tile built-in.
It's really great, however there is something i would suggest to add:

Could it be possible to remove app from the launcher after successful setup or maybe add a toggle in settings to hide it from drawer like it's possible with Gboard and Digital Wellbeing? The icon in drawer becomes pretty much useless after giving it permissions and some people prefer to have clean homescreen.

Thanks for great app again!

**Comment by grmasa** [comment]
According to [this](https://developer.android.com/reference/android/content/pm/LauncherApps#getActivityList(java.lang.String,%20android.os.UserHandle)) it's not possible after API 29
